export enum Category {
  UNIVERSO_VINGADORES = 'UNIVERSO_VINGADORES',
  UNIVERSO_HOMEM_ARANHA = 'UNIVERSO_HOMEM_ARANHA',
  UNIVERSO_X_MEN = 'UNIVERSO_X_MEN',
  UNIVERSO_DEMOLIDOR = 'UNIVERSO_DEMOLIDOR',
  OUTROS = 'OUTROS'
}
